// The single source of truth for all property data
const properties = [
    { id: 1, title: 'Godrej Evergreen Square', city: 'Pune', price: '1.5 Cr', bhk: '3 BHK', image: '/assets/images/property/property1.jpg', detailsUrl: 'whatsapp', brochureUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf?property=1' },
    { id: 2, title: 'Godrej Carnival', city: 'Pune', price: '50 Lakh', bhk: '4 BHK', image: '/assets/images/property/property2.jpg', detailsUrl: 'whatsapp', brochureUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf?property=2' },
    { id: 3, title: 'Godrej Exquisite', city: 'Thane', price: 'Under 50 Lakh', bhk: '1 RK', image: '/assets/images/property/property3.jpg', detailsUrl: 'whatsapp', brochureUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf?property=3' },
    { id: 4, title: 'Gogrej Forest Estate', city: 'Nagpur', price: '4 Cr', bhk: '5 BHK', image: '/assets/images/property/property4.jpg', detailsUrl: 'whatsapp', brochureUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf?property=4' },
    { id: 5, title: 'Godrej Hinjawadi Park World', city: 'Pune', price: '1.5 Cr', bhk: '4 BHK', image: '/assets/images/property/property5.jpg', detailsUrl: 'whatsapp', brochureUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf?property=5' },
    { id: 6, title: 'Godrej Hinjewadi Aqua', city: 'Pune', price: '1 Cr', bhk: '3 BHK', image: '/assets/images/property/property6.jpg', detailsUrl: 'whatsapp', brochureUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf?property=6' },
    { id: 7, title: 'Godrej Regal Pavilion', city: 'Hyderabad', price: '2.5 Cr', bhk: '3 BHK', image: '/assets/images/property/property7.jpg', detailsUrl: 'whatsapp', brochureUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf?property=7' },
    { id: 8, title: 'Godrej Reserve', city: 'Mumbai', price: '3.75 Cr', bhk: '1BHK - 4BHK', image: '/assets/images/property/property8.jpg', detailsUrl: 'whatsapp', brochureUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf?property=8' },
    { id: 9, title: 'Godrej Woodside Estate', city: 'Navi Mumbai', price: '4.5 Cr', bhk: '5 BHK', image: '/assets/images/property/property9.jpg', detailsUrl: 'whatsapp', brochureUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf?property=9' },
    { id: 10, title: 'Godrej Zen Estate', city: 'kolkata', price: '45 Lakh', bhk: '1 BHK', image: '/assets/images/property/property10.jpg', detailsUrl: 'whatsapp', brochureUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf?property=10' },
    { id: 11, title: 'Godrej Greenview', city: 'Indore', price: '3.2 Cr', bhk: '4 BHK', image: '/assets/images/property/property11.jpg', detailsUrl: 'whatsapp', brochureUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf?property=11' },
    { id: 12, title: 'Greeen Terrace', city: 'Navi Mumbai', price: '60 Lakh', bhk: '1 BHK', image: '/assets/images/property/property12.jpg', detailsUrl: 'whatsapp', brochureUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf?property=12' },
    { id: 13, title: 'Khopoli Hillview', city: 'Navi Mumbai', price: '3.8 Cr', bhk: '4 BHK', image: '/assets/images/property/property13.jpg', detailsUrl: 'whatsapp', brochureUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf?property=13' },
    { id: 14, title: 'Godrej Bayview', city: 'Navi Mumbai', price: '3.20 Cr', bhk: '1BHK - 3BHK', image: '/assets/images/property/property14.jpg', detailsUrl: 'whatsapp', brochureUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf?property=14' },
    { id: 15, title: 'Godrej plot', city: 'Ahmedabad', price: '5 Cr', bhk: '6 BHK', image: '/assets/images/property/property15.jpg', detailsUrl: 'whatsapp', brochureUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf?property=15' },
];
